"""Energy baseline + transparent anomaly rules. Readings are SIMULATED sample data in this prototype."""
from datetime import timedelta
from statistics import median
from .util import parse_iso, iso

WARN_RATIO, CRIT_RATIO, SUSTAINED_HOURS, MIN_REF = 1.25, 1.5, 3, 3
RULES = [f"Baseline = median kWh of the same building at the same hour-of-day over reference days (all data before the evaluation window; needs >= {MIN_REF} points).",
         f"Hour is anomalous when observed/baseline >= {WARN_RATIO} (warning) or >= {CRIT_RATIO} (critical).",
         f"Consecutive anomalous hours form one event; an event lasting >= {SUSTAINED_HOURS} hours is escalated to critical.",
         "Excess kWh = sum(observed - baseline) over the event. It is an estimate vs. baseline, not a verified saving."]

def baselines(readings, window_start):
    ref = {}
    for r in readings:
        t = parse_iso(r["ts"])
        if t < window_start: ref.setdefault((r["building"], t.hour), []).append(r["kwh"])
    return {k: median(v) for k, v in ref.items() if len(v) >= MIN_REF}

def detect(readings, window_start):
    """Pure function: readings=[{building,ts,kwh}] -> list of anomaly events inside [window_start, end]."""
    base = baselines(readings, window_start)
    by_b = {}
    for r in readings:
        t = parse_iso(r["ts"])
        if t >= window_start: by_b.setdefault(r["building"], []).append((t, r["kwh"]))
    events = []
    for b, pts in sorted(by_b.items()):
        pts.sort(); run = []
        def close():
            if not run: return
            hrs = len(run); peak = max(run, key=lambda x: x[3])
            excess = round(sum(o - bl for _, o, bl, _ in run), 1)
            sev = "critical" if (hrs >= SUSTAINED_HOURS or peak[3] >= CRIT_RATIO) else "warning"
            events.append({"building": b, "start": iso(run[0][0]), "end": iso(run[-1][0]), "hours": hrs,
                           "peak_observed_kwh": round(peak[1], 1), "baseline_kwh": round(peak[2], 1),
                           "peak_ratio": round(peak[3], 2), "excess_kwh_est": excess, "severity": sev,
                           "recommended_action": ("Dispatch a check of HVAC/lighting schedules and after-hours loads in " + b +
                                                  ("; a sustained multi-hour draw suggests equipment or HVAC left running." if hrs >= SUSTAINED_HOURS else "; monitor next hours.")),
                           "evidence": f"{hrs}h with observed/baseline >= {WARN_RATIO}; peak {peak[1]:.1f} kWh vs baseline {peak[2]:.1f} kWh"})
            run.clear()
        prev = None
        for t, kwh in pts:
            bl = base.get((b, t.hour))
            ratio = (kwh / bl) if bl else 0
            flagged = bl is not None and ratio >= WARN_RATIO
            contiguous = prev is not None and t - prev == timedelta(hours=1)
            if flagged:
                if run and not contiguous: close()
                run.append((t, kwh, bl, ratio))
            else: close()
            prev = t
        close()
    return events

def load(conn):
    return [dict(r) for r in conn.execute("SELECT building,ts,kwh,simulated FROM energy_readings ORDER BY ts")]

def summary(conn, now):
    rd = load(conn)
    if not rd: return {"buildings": [], "anomalies": [], "simulated": True, "note": "No readings loaded.", "rules": RULES}
    end = max(parse_iso(r["ts"]) for r in rd)
    ws = end - timedelta(hours=23)
    base = baselines(rd, ws)
    events = detect(rd, ws)
    blds = {}
    for r in rd:
        t = parse_iso(r["ts"])
        if t >= ws:
            d = blds.setdefault(r["building"], {"building": r["building"], "series": [], "total_24h_kwh": 0.0, "baseline_24h_kwh": 0.0})
            bl = base.get((r["building"], t.hour))
            d["series"].append({"ts": r["ts"], "kwh": round(r["kwh"], 1), "baseline": round(bl, 1) if bl else None})
            d["total_24h_kwh"] += r["kwh"]
            if bl: d["baseline_24h_kwh"] += bl
    out = []
    for b, d in sorted(blds.items()):
        d["total_24h_kwh"] = round(d["total_24h_kwh"], 1); d["baseline_24h_kwh"] = round(d["baseline_24h_kwh"], 1)
        d["ratio"] = round(d["total_24h_kwh"] / d["baseline_24h_kwh"], 2) if d["baseline_24h_kwh"] else None
        d["anomaly_events"] = sum(1 for e in events if e["building"] == b)
        out.append(d)
    return {"window_start": iso(ws), "window_end": iso(end), "buildings": out, "anomalies": events,
            "simulated": bool(any(r["simulated"] for r in rd)),
            "provenance": "SIMULATED sample readings generated by the seed script - not from real meters.", "rules": RULES}
